name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Hub
        env:
            HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Set up Git identity (Hugging Face)
          git config --global user.email "dinhhai1ccg@gmail.com"
          git config --global user.name "1-13-am"

          # Add Hugging Face remote
          git remote add huggingface https://user:${HF_TOKEN}@huggingface.co/spaces/1-13-am/lumina-early-proto

          # Force push to Hugging Face 
          git push huggingface main --force
